# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(458, 427)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.text = QtWidgets.QTextBrowser(self.centralwidget)
        self.text.setGeometry(QtCore.QRect(45, 20, 381, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.text.setFont(font)
        self.text.setObjectName("text")
        self.btc = QtWidgets.QPushButton(self.centralwidget)
        self.btc.setGeometry(QtCore.QRect(60, 130, 351, 31))
        self.btc.setObjectName("btc")
        self.yo = QtWidgets.QPushButton(self.centralwidget)
        self.yo.setGeometry(QtCore.QRect(60, 180, 351, 31))
        self.yo.setObjectName("yo")
        self.ltc = QtWidgets.QPushButton(self.centralwidget)
        self.ltc.setGeometry(QtCore.QRect(60, 230, 351, 31))
        self.ltc.setObjectName("ltc")
        self.doge = QtWidgets.QPushButton(self.centralwidget)
        self.doge.setGeometry(QtCore.QRect(60, 280, 351, 31))
        self.doge.setObjectName("doge")
        self.dash = QtWidgets.QPushButton(self.centralwidget)
        self.dash.setGeometry(QtCore.QRect(60, 330, 351, 31))
        self.dash.setObjectName("dash")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Currency", "Currency"))
        self.btc.setText(_translate("MainWindow", "GET_BTC_USD"))
        self.yo.setText(_translate("MainWindow", "GET_YO_USD"))
        self.ltc.setText(_translate("MainWindow", "GET_LTC_USD"))
        self.doge.setText(_translate("MainWindow", "GET_DOGE_USD"))
        self.dash.setText(_translate("MainWindow", "GET_DASH_USD"))
